# Generated by Django 5.0.3 on 2024-05-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reciepes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciepe_name', models.CharField(max_length=50)),
                ('reciepe_desc', models.TextField()),
                ('reciepe_img', models.ImageField(upload_to='reciepe_images')),
            ],
        ),
    ]
